# Generated by Django 2.2.3 on 2019-08-27 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='品牌名')),
                ('initial', models.CharField(default='', max_length=50, verbose_name='品牌名的拼音/英文名首字母')),
                ('image_filename', models.CharField(default='', max_length=50, verbose_name='品牌图片名')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likename', models.CharField(max_length=50, verbose_name='喜好')),
            ],
            options={
                'db_table': 'Like',
                'verbose_name': '喜好',
                'verbose_name_plural': '喜好',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('use_time', models.DateTimeField(auto_now_add=True, verbose_name='最近登录时间')),
                ('born_time', models.DateTimeField(auto_now_add=True, verbose_name='出生日期')),
                ('sex', models.CharField(default='', max_length=50, verbose_name='性别')),
                ('job', models.CharField(max_length=50, verbose_name='职业')),
                ('state_info', models.BooleanField(blank=True, verbose_name='信息是否完善')),
                ('img_head', models.CharField(default='', max_length=256, verbose_name='头像')),
                ('area', models.CharField(default='', max_length=50, verbose_name='地区')),
                ('driver_licence', models.CharField(default='', max_length=256, verbose_name='行驶证')),
                ('driver_license', models.CharField(default='', max_length=256, verbose_name='驾驶证')),
                ('sign', models.CharField(default='', max_length=50, verbose_name='星座')),
                ('fan', models.ManyToManyField(to='user.Like', verbose_name='喜好')),
            ],
            options={
                'db_table': 'User',
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sample2', to='user.User', verbose_name='被关注者用户ID')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sample1', to='user.User', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(default='', max_length=50, verbose_name='话题名称')),
                ('topic_time', models.DateTimeField(auto_now_add=True, verbose_name='话题发布时间')),
                ('topic_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='话题发布人')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=256, verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='图片上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户ID')),
            ],
            options={
                'db_table': 'Image',
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='CarSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='车系名')),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.CarBrand', verbose_name='所属品牌id')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='车型名称')),
                ('price', models.CharField(default='', max_length=50, verbose_name='车型上市时指导价格（w）')),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.CarBrand', verbose_name='所属品牌id')),
                ('series', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.CarSeries', verbose_name='所属车系id')),
            ],
        ),
        migrations.CreateModel(
            name='CarBarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.CarModel', verbose_name='所属车型id')),
                ('car_person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sample3', to='user.User', verbose_name='第一人称ID')),
                ('third_person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sample4', to='user.User', verbose_name='第三人称ID')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_kind', models.CharField(default='', max_length=50, verbose_name='活动类型种类(单人/多人)')),
                ('activity_time', models.DateTimeField(auto_now_add=True, verbose_name='活动时间')),
                ('activity_area_start', models.CharField(default='', max_length=50, verbose_name='活动出发地')),
                ('activity_area_end', models.CharField(default='', max_length=50, verbose_name='活动目的地')),
                ('activity_person_sex', models.CharField(default='', max_length=50, verbose_name='活动参与人群性别')),
                ('activity_person_num', models.CharField(default='', max_length=50, verbose_name='活动参与人群人数')),
                ('activity_img', models.CharField(default='', max_length=256, verbose_name='活动添加图片')),
                ('activity_content', models.TextField(default='', verbose_name='说说你的想法')),
                ('activity_status', models.CharField(default='', max_length=50, verbose_name='活动状态')),
                ('activity_car', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.CarBarn', verbose_name='我的出行车辆')),
                ('activity_issue', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sample5', to='user.User', verbose_name='活动发布人')),
                ('activity_join', models.ManyToManyField(default='', related_name='sample6', to='user.User', verbose_name='活动参与者')),
                ('activity_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Like', verbose_name='活动名称')),
            ],
        ),
    ]
