# Generated by Django 2.2.3 on 2019-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190829_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin',
            field=models.CharField(default='', max_length=50, verbose_name='点数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state_info',
            field=models.CharField(default='', max_length=50, verbose_name='信息是否完善'),
        ),
    ]
