# Generated by Django 2.2.3 on 2019-09-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190905_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_coin_take',
            field=models.CharField(default='', max_length=50, verbose_name='活动参与点数'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_person_take',
            field=models.CharField(default='', max_length=50, verbose_name='活动携带人数'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_person_num',
            field=models.CharField(default='', max_length=50, verbose_name='活动参与人群参与车辆'),
        ),
    ]
