# Generated by Django 2.2.3 on 2019-09-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190905_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='topic_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Topic', verbose_name='话题名称'),
        ),
    ]
