# Generated by Django 2.2.3 on 2019-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_activity_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='latitude_end',
            field=models.CharField(default='', max_length=50, verbose_name='终点纬度'),
        ),
        migrations.AddField(
            model_name='activity',
            name='latitude_start',
            field=models.CharField(default='', max_length=50, verbose_name='起始点纬度'),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude_end',
            field=models.CharField(default='', max_length=50, verbose_name='终点经度'),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude_start',
            field=models.CharField(default='', max_length=50, verbose_name='起始点经度'),
        ),
    ]
