# Generated by Django 2.2.3 on 2019-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190910_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_time',
            field=models.DateTimeField(verbose_name='活动时间'),
        ),
    ]
