# Generated by Django 2.2.3 on 2019-09-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190911_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='BJImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=256, verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='图片上传时间')),
                ('activity', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '背景图片',
                'db_table': 'BJImage',
                'verbose_name_plural': '背景图片',
            },
        ),
    ]
