# Generated by Django 2.2.3 on 2019-09-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_bjimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_img',
        ),
    ]
