# Generated by Django 2.2.3 on 2019-09-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_activity_activity_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bjimage',
            old_name='activity',
            new_name='user',
        ),
    ]
