# Generated by Django 2.2.3 on 2019-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190912_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间'),
        ),
    ]
