# Generated by Django 2.2.3 on 2019-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_activity_activity_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_score',
            field=models.CharField(default='', max_length=50, verbose_name='颜值'),
        ),
    ]
