# Generated by Django 2.2.3 on 2019-09-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_face_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_status',
            field=models.CharField(default='', max_length=20, verbose_name='审核状态'),
        ),
    ]
