# Generated by Django 2.2.3 on 2019-09-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190927_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='driver_licence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license',
        ),
        migrations.AddField(
            model_name='carbarn',
            name='driver_licence',
            field=models.CharField(default='', max_length=256, verbose_name='行驶证'),
        ),
        migrations.AddField(
            model_name='carbarn',
            name='driver_license',
            field=models.CharField(default='', max_length=256, verbose_name='驾驶证'),
        ),
    ]
